### ISSUE TITLE
Problems with Macbook Pro

### ISSUE THREAD

**Issue by Jodaucon** [tjakubo2/TTS_xwing#10]
Hi,

I'm having this error with mac

"error: 14077438:ssl routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error"

I cannot see the ships and the computer heats a lot.

Thank you.

**Comment by tjakubo2** [comment]
Hey, this is a known issue with Unity where links starting with http**s** are not loading. There is a very old bug report on TTS forums but looks like devs aren't really prioritising it.

This will be fixed in the next release of the table (as a new workshop item to let me update it directly) but I can't say when it will happen (this week hopefully?).

For now, you can use these saves:
[TTS_Xwing_macfix.zip](https://github.com/tjakubo2/TTS_xwing/files/564189/TTS_Xwing_macfix.zip)
Unzip the archive and paste the .json files to C:\Users\[username]\Documents\My Games\Tabletop Simulator\Saves
Then, in game, instead of selecting workshop -> table, use load game -> select one of these two saves (table_http or spawner_http). These should not error out.

Bear in mind that people coming to your table can bring their own lists with models using https links that will not load for you (or act weird, infinitely falling if it;s just collider with https link) - we can't do anything about it, they should use the spawner from your save to make them work. 

Neither this nor any heating issues we can't fix directly, it's problems with TTS/Unity. Make sure you patch in at the official Berserk forums bug report so devs know this is a important issue!

Cheers!

**Comment by Jodaucon** [comment]
Thanks.

Will try it.

Thanks again.

El dia 1 nov. 2016 15:11, "tjakubo2" <notifications@github.com> va escriure:

**Comment by mjones329** [comment]
Seems to still be an issue. I think this is similar to what I am experiencing (see recent new issue.) I am also on a Mac. I can spawn a table and a list spawner without error using the zip files above, but I still cannot see ship models.

**Comment by tjakubo2** [comment]
Just to round this issue up: this is a problem with TTS/Unity not being able to use SSL properly. Fix: do not use https links in stuff.

How to make the error go away (any kind of save/game):
1. Save the game
2. Open newly created save file (C:\Users[username]\Documents\My Games\Tabletop Simulator\Saves) with Notepad++ or similiar text editor
3. Search for 'https', replace all occurences with 'http'
4. Save the file
5. Load it up in-game
(6). Read up other comments on this issue in this thread
(7). Post here if stuff stil breaks

**Comment by tjakubo2** [comment]
Should be solved now. Both the table and spawner are updated with all https-free links. Code in repo is not updated since it is pain in the ass to sync it with the TTS temporary scripting folder. Repo update will be sorted out... soon.

**Comment by mjones329** [comment]
Wow!  That's amazing!  I will love to be able to play x-Wing on TTS!  Thanks for the update. I had pretty much written off the possibility to play on there!  

    On Thursday, January 12, 2017 6:36 PM, tjakubo2 <notifications@github.com> wrote:
 

 Should be solved now. Both the table and spawner are updated with all https-free links. Code in repo is not updated since it is pain in the ass to sync it with the TTS temporary scripting folder. Repo update will be sorted out... soon.—

**Comment by tjakubo2** [comment]
Yes, exactly. Sucks for spectating, but hopefully over time people will fill their chests with lists built with SSL-safe spawner. If someone joins your table and pulls out a htpps linked list, you can use the spawner directly on table to rebuild it :)
