### ISSUE TITLE
OSX - Error calling Lua function toggleRulers: 

### ISSUE THREAD

**Issue by enderSFTD** [tjakubo2/TTS_xwing#12]
OSX - Error calling Lua function toggleRulers: 

When pushing the button for the 3rd time to make them disaper you get this error and then the red rulers are stuck

Thanks :)

**Comment by tjakubo2** [comment]
Hey, thanks for the report!
Figured it out, turns out TTS update changed *something* and table entries were not deleted properly. Apparently [one of the simple methods ](http://stackoverflow.com/questions/4880368/how-to-delete-all-elements-in-a-lua-table)for clearing a table is not working now.
So instead of

    for key, entry in pairs(myTable) do
      -- do stuff with entry
      myTable[key] = nil 
    end
you have to do

    for key, entry in pairs(myTable) do
      -- do stuff with entry
    end
    myTable = {}
to properly iterate over a table and clear it, first method will make next iteration go over old elements again. Not a Lua expert so no idea on how this differs but seems to work identically and well, it doesn't error out on the newest TTS.

Commit and update will follow (hopefully) shortly, sadly I can't directly update the table :(

**Comment by tjakubo2** [comment]
With the most recens, **AMAZING** TTS update, Berserk fixes some Lua inconsistencies and this disappeared :)

Also floating ships bug and I can focus on this more.
