### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by alexsavickiy** [tjakubo2/TTS_xwing#13]
Hello.
Iam linux user and now i have ssl errors when models trying to load. Screanshot attached
![286160_screenshots_20170212201948_1](https://cloud.githubusercontent.com/assets/25725747/22864375/4ad79b16-f161-11e6-816b-54c8779e89f1.jpg)

**Comment by tjakubo2** [comment]
Caused by https links, rehost to http stuff in progress.

A homebrew solution may be using [TTS Mod Backup tool](http://www.nexusmods.com/tabletopsimulator/mods/263/?) to download all files locally (Mods tab on the left window, find and click this mod then Doanload All in the right window, wait till it finishes) and then checking the "Mod Caching" option in TTS (Menu-> Configuration).

**Comment by tjakubo2** [comment]
Content rehosted, should be no SSL error on the pre-release table:
http://steamcommunity.com/sharedfiles/filedetails/?id=862644552
(friends only visibility, [add me ](steamcommunity.com/id/dzikakulka)to help testing it)

This table will be publicly released once properly tested.
