### ISSUE TITLE
Barrel rolling into ships is not prevented

### ISSUE THREAD

**Issue by jbuckland** [tjakubo2/TTS_xwing#2]
The table allows you to do a barrel roll action into another ship, causing you to land on top of the other ship. However if you try to boost into another ship the table will cause you to "bump" the other ship.

**Comment by tjakubo2** [comment]
Kinda forgot about it. It works this way since boost simply reuses straight/bank 1 manuever (that has collisions as normal) but roll, being a special snowflake and never allowing for partial movement due to collision, just goes ham.

I had an idea about making roll move to nearest available offset if obstructed, but not only it wouldn't fully comply with rules (you are commited to roll only for the template you place down) but would also be kinda non-obvious what's going on.

If you have suggestions on how this should work, let me know!

**Comment by tjakubo2** [comment]
Implemented in v1.1
