### ISSUE TITLE
Obstacles too thin

### ISSUE THREAD

**Issue by JohnnyCheese** [tjakubo2/TTS_xwing#21]
When overlapping an obstacle, the ship is almost completely flat on the board. On close calls, due to the limited camera, it's pretty hard to check if the ship is overlapping the obstacle.

If the obstacles token were a little bit thicker, just a few milimeters, the overlapping would be more obvious and easily spotted. 

If you sclae the asteroid on the proper axis manualy, you can check for overlaps easily, but it wouldnt be necessary if the obstacles where a little thicker, no more than a 1/5 of the shp's base height..

**Comment by tjakubo2** [comment]
No prob, just did that. Let me know if I should increase it more (you can comment on closed issue no prob, it will reopen and notify me). Sadly debris fields can't be scaled on separate axes since they are "Token" type (there's no explicit models for them) so they are still thick and ugly.

And sorry for delays on everything else. Uni is killing me for now. Hopefully this will change soon.
