### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by Vanguard76** [tjakubo2/TTS_xwing#24]
The following will not load when I start the module.

http://sites.google.com/site/jeuxdemorvana/home/D8e.jpg
http://sites.google.com/site/jeuxdemorvana/home/D8.jpg
http://www.fotos-hochladen.net/uploads/textokeno3m724jv65.png
http://i.imgur.com/UcxzKoW.png
http://i.imgur.com/Ocbzd25.png
http://img4.fotos-hochladen.net/uploads/bluetlsnqhwg09by.jpg

**Comment by tjakubo2** [comment]
If they work for you when you open them in browser, not much I (as a mod creator) can do, it's TTS issue. Especially since there are other assets on these hosting sites so they aren't down or something for a rehost to be needed.

Try deleting everything in Documents\My Games\Tabletop Simulator\Mods\Images. Enable mod caching and disable threading in options. Check your firewall.

**Comment by tjakubo2** [comment]
Since there's no response and TTS just got an update that is supposed to fix some loading issues, I'm closing this. Comment and reopen if you have more specific info on that (at least OS, if these load in browser, if you tried removing cache and disabling caching etc).
