### ISSUE TITLE
pastebin error

### ISSUE THREAD

**Issue by dudurban** [tjakubo2/TTS_xwing#30]
Hi, 

Lately I've had problems loading the table. 

The error, shown in the image below, happens as soon as the MOD is loaded. 

Any clue why this has happened?

Thanks for the attention.

Dudu Urban

![image](https://cloud.githubusercontent.com/assets/29049038/26560927/7721dc40-4490-11e7-9f1e-c2c6a670b7ad.png)

**Comment by tjakubo2** [comment]
Looks like you can't conect to pastebin. Can you copy each of these two pastebin links that are in this window, paste them in your browser and let me know if they opened OK? They should load a plain page with some text and numbers.

**Comment by dudurban** [comment]
Yep, I can't connect at pastebin.

I do copy and paste on browser http://pastebin.com/raw.php?i=VjZhkJSi, and return that:

![image](https://cloud.githubusercontent.com/assets/29049038/26564111/2365e56a-44b3-11e7-89af-51b1dbc4c05f.png)

Connection timed out....

**Comment by tjakubo2** [comment]
Sadly, I can view that link so there's some connection issues with your computer/router. Aside from trying to disable your firewall (Winds firewall or antivirus firewall, not the antivirus itself though of course), resetting your router... I don't really know how to fix it. You could try and contact your ISP since this link is definitely up.

As a workaround, I can try and send you my cached files to put in Tabletop Sim cache folder so they are loaded locally instead of from pastebin. Ill post that and instructions in a new comment here soon.

**Comment by tjakubo2** [comment]
(for some reason github won't let me attach a zip)
So, to be able to play X-Wing on TTS regardless of these problems, follow this:

1. Download: https://drive.google.com/file/d/0B5NQRbuc_G9gbEE4NzV3WHEya1k/view?usp=sharing  
2. Put it in the Documents\My Games\Tabletop Simulator\Mods\Models folder.  
3. Extract it, all the models should be directly in above directory, no subfolders inside.  
4. Launch TTS, click Configuration, tick "Mod Caching" if it's not on.  
5. Load up the mod.  

Please let me know if this worked for you :)

**Comment by dudurban** [comment]
HI!! 

That works!!!

 Thanks for your help!

![image](https://cloud.githubusercontent.com/assets/29049038/26607703/33e94312-456e-11e7-8b24-8dfe2cbab50a.png)

**Comment by tjakubo2** [comment]
Happy to help :)
