### ISSUE TITLE
Dials disappearing after clicking delete button.

### ISSUE THREAD

**Issue by Lysus** [tjakubo2/TTS_xwing#39]
**What happened:**
Miranda's dials turned invisible after clicking the "Delete" button on the dial.  They were still present and could be moused over and interacted with.  After flipping the dial twice, it would become visible again.

**What was supposed to happen:**
Miranda's dials stay visible the whole time.

**How to make this happen:**
It happened every time I created a new set of dials in this lobby, but I haven't had time to go back and see if I can reproduce it yet.

**Does this still occur after saving & loading game:**
Don't know.

**Comment by tjakubo2** [comment]
Self note: this is probably caused by dials getting sinked "into the table" for some reason. Different from #7 since they are still there. I'll try to force constant dial height.

**Comment by tjakubo2** [comment]
Turns out it wasn't that hard to reproduce, heh. Just had to throw few dials around. This is a very unfriendly bug since it kinda stems from TTS physics (returned dials get pushed "into" the table if others align to block it slightly), but little bit of duckt tape apparently helped.

I can't reproduce this anymore (on 1.1.26.2 v2) but let me know if this pops up again, save the game too then.
