### ISSUE TITLE
no 'storedials' command that shows the range 1 circle

### ISSUE THREAD

**Issue by jbuckland** [tjakubo2/TTS_xwing#4]
I personally liked the range 1 circle for when I missed a dial or two when doing 'sd'. The range circle helped my know how to adjust the placement of my ship to get all the dials in the circle.

I wouldd consider this a 'nice to have', and not a major bug.

**Comment by tjakubo2** [comment]
This was left out since not only it didn't show accurately which dials were saved - the guide was bomb range ruler copied and scaled, the real saving criteria was distance from center of ship making it a circle, not the rounded square the guide was - but also beacause the circle distance choosing which dials to save is suboptimal. 
It is planned to make the dials choosing systems smarter, for example: being aware of the dials scale (dials scaled down and grouped tightly can be problematic now) and adjusting the "saving area" rectangle (no reason to keep it circle shaped) to reach sideways as far as turn dials go and forward/backward as far as speed 0-5 stretches. 

That said, showing saving area would be useful aswell and definitely needed in testing so it would be left under some command too. Preferably with button shapes depicting it instead of a model to make this purely script based.

**Comment by tjakubo2** [comment]
Looks like I can't make a commit just reference an issue, only immediately close it too. But well, saving area depiction has been added and this resolved, so it's kinda OK.

**Comment by tjakubo2** [comment]
This is online on the workshop table now. 

'storedials' is unavailable, equivalent functions are:
'sd' - show saving area guides and save all dials inside
'cd' - only show saving area guides
'rd' - remove all assigned dials
