### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by ImTheRhino** [tjakubo2/TTS_xwing#59]
Is there a way to change the board for Epic play?

Cheers

**Comment by tjakubo2** [comment]
Gotta use the Gizmo tool to move stuff around, sink the current playmats in or scale them up to Epic proportions. Sorry for being super late, my RSS feed broke I think since it's not listing issues at all anymore.

There were plans for Epic layouts but scripting in TTS is hard to work with, I may have hit a point where more complex is just too much for me to wrap my head around (with the current scripting environment with such limited API, basic Lua tools cut out for no reason, same bugs for years, new bugs every update et cetera).

**Comment by ImTheRhino** [comment]
No problem mate.

Was just a thought as a couple of us were throwing around how good it would be to play epic point games (no necessarily with the epic ship models) on an epic size mat.

Cheers.

**Comment by tjakubo** [comment]
Closing this since we probably won;t be getting any extra features into this mod
