### ISSUE TITLE
Range / Arc Rulers not showing in Top Down Camera Perspective

### ISSUE THREAD

**Issue by mrtobacco** [tjakubo2/TTS_xwing#68]
Just toying around with your mod, so far it seems great thanks alot.

Any chance to fix the range / firering arc rulers not showing while in "Top Down" Camera View ?

ty

**Comment by tjakubo** [comment]
Hey, that's because they're actually zero pixels thick (two flipped faces in the same place). This was done as a feature since "zero width" ruler raises no questions like "if a ship clips the inside of a ruler but doesn't stick out on the other side, is it in or not....". That was a real problem with previous version of rulers.

So far I'm experimenting and sadly not even highlight on them is visible when viewed from top-down perspective. I've made a simple script that will wiggle the arcs so they are *sometimes* visible from top-down, here are instructions:

1. Download and unpack [swayRulers.zip](https://github.com/tjakubo2/TTS_xwing/files/2502535/swayRulers.zip)
2. Copy and paste the ``swayRulers.json`` to ``MyDocuments/MyGames/TabletopSimulator/Saves/SavedObjects``
3. In-game, open Objects -> Saved Objects and drag the "swayRulers" checkers onto the table anywhere.
4. While the checker is there, rulers should wiggle around so they are kinda visible from top down.

**Comment by tjakubo** [comment]
I've experimented with it a bit and have no idea how to make them show up properly without making them thick (which is much more problematic then). Closing this for now, hopefully the workaround script will be enough.
